- name : Variables from separate file
  hosts: local
  connection: local
  vars_files:
    - details.yaml

  tasks:
  - name: print Course information
    ansible.builtin.debug:
      msg: "Hello every one i'm {{ TRAINER }} Trainer of {{ COURSE }} and Duration of the Course is {{ DURATION }}"
    
  - name: addition of two numbers
    ansible.builtin.debug:
      msg : " {{ LISTENER }} is seeing Addition  of {{ A_Number }} and {{ B_Number }} is {{A_Number+B_Number}}"

  - name: addition of two numbers
    ansible.builtin.debug:
      msg : " {{ LISTENER }} is seeing Addition  of {{ num1 }} and {{ num2 }} is {{num1+num2}}"