- name: preference of vars 
  hosts: local
  connection: local
  vars:
    GREETING: "Hello from Play Vars"
  
  vars_files:
    - details.yaml
  
  vars_prompt:
    - name: GREETING
      prompt: please enter the greetings

  tasks:
  - name: print the greetings
    # vars:
    #   GREETING: "Hello from Task Vars"
    ansible.builtin.debug:
      msg : "{{ GREETING }}"