- name : installation of multiple packages at once 
  hosts : local
  become: yes
  tasks: 
  - name : "installation of {{ item }}"
    ansible.builtin.dnf :
      name: "{{ item }}"
      state: installed
    loop:
    - nginx
    - httpd
    - zip
    - git
    - vim