- name : functions
  hosts : local
  connection : local
  tasks :
  - name : default value assigning to vars if not defined any where
    ansible.builtin.debug:
    msg : " Hello, {{ person | default(' ramesh ')}}"

  - name : print names
    vars:
      person: "suresh, shiva, anjii, ram"
      ansible.builtin.debug:
        msg : "{{ person | split(',')}}"

  - name : convert map into list
    vars:
      course:
        name: ansible
        duration: 10Hr
        trainer: sivakumar
      ansible.builtin.debug:              # error occurred
        msg : "course Info : {{ course | dict2item }}"

  - name : convert list into map 
    vars:
    course:
      - { 'key': 'name', 'value' : 'ansible' } 
      - { 'key': 'duration', 'value' : '10Hr' } 
      - { 'key': 'trainer', 'value' : 'sivakumar' } 
    ansible.builtin.debug:           
      msg : "course Info : {{ course | item2dict }}"

